<?php
namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * command: php artisan db:seed --class=PermissionsSeeder
     */
    public function run(): void
    {
        $timestamp  = now();
        $createDate = date('Y-m-d H:i:s');

        $permissions = [
            [
                'name'         => 'dashboard_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'dashboard',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'role_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'roles',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'role_list',
                'display_name' => 'List Roles',
                'guard_name'   => 'web',
                'group_name'   => 'roles',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'role_create',
                'display_name' => 'Create Role',
                'guard_name'   => 'web',
                'group_name'   => 'roles',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'role_edit',
                'display_name' => 'Edit Role',
                'guard_name'   => 'web',
                'group_name'   => 'roles',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'role_delete',
                'display_name' => 'Delete Role',
                'guard_name'   => 'web',
                'group_name'   => 'roles',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'role_show',
                'display_name' => 'View Role',
                'guard_name'   => 'web',
                'group_name'   => 'roles',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'user_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'user',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'user_list',
                'display_name' => 'List Users',
                'guard_name'   => 'web',
                'group_name'   => 'user',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'user_create',
                'display_name' => 'Create User',
                'guard_name'   => 'web',
                'group_name'   => 'user',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'user_edit',
                'display_name' => 'Edit User',
                'guard_name'   => 'web',
                'group_name'   => 'user',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'user_delete',
                'display_name' => 'Delete User',
                'guard_name'   => 'web',
                'group_name'   => 'user',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'user_show',
                'display_name' => 'View User',
                'guard_name'   => 'web',
                'group_name'   => 'user',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            // Pages
            [
                'name'         => 'page_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'pages',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'page_list',
                'display_name' => 'List Pages',
                'guard_name'   => 'web',
                'group_name'   => 'pages',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'page_create',
                'display_name' => 'Create Page',
                'guard_name'   => 'web',
                'group_name'   => 'pages',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'page_edit',
                'display_name' => 'Edit Page',
                'guard_name'   => 'web',
                'group_name'   => 'pages',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'page_delete',
                'display_name' => 'Delete Page',
                'guard_name'   => 'web',
                'group_name'   => 'pages',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'page_show',
                'display_name' => 'View Page',
                'guard_name'   => 'web',
                'group_name'   => 'pages',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'page_toggle_status',
                'display_name' => 'Toggle Page Status',
                'guard_name'   => 'web',
                'group_name'   => 'pages',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],

            // Email Templates
            [
                'name'         => 'email_template_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'email_templates',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'email_template_list',
                'display_name' => 'List Email Templates',
                'guard_name'   => 'web',
                'group_name'   => 'email_templates',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'email_template_create',
                'display_name' => 'Create Email Template',
                'guard_name'   => 'web',
                'group_name'   => 'email_templates',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'email_template_edit',
                'display_name' => 'Edit Email Template',
                'guard_name'   => 'web',
                'group_name'   => 'email_templates',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'email_template_delete',
                'display_name' => 'Delete Email Template',
                'guard_name'   => 'web',
                'group_name'   => 'email_templates',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'email_template_show',
                'display_name' => 'View Email Template',
                'guard_name'   => 'web',
                'group_name'   => 'email_templates',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'email_template_toggle_status',
                'display_name' => 'Toggle Email Template Status',
                'guard_name'   => 'web',
                'group_name'   => 'email_templates',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],

            // Settings & related
            [
                'name'         => 'setting_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'settings',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'setting_update',
                'display_name' => 'Update Settings',
                'guard_name'   => 'web',
                'group_name'   => 'settings',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],

            // Visibility settings
            [
                'name'         => 'visibility_view',
                'display_name' => 'View Visibility Settings',
                'guard_name'   => 'web',
                'group_name'   => 'visibility',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'visibility_update',
                'display_name' => 'Update Visibility Settings',
                'guard_name'   => 'web',
                'group_name'   => 'visibility',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],

            // Shifts
            [
                'name'         => 'shift_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'shifts',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'shift_list',
                'display_name' => 'List Shifts',
                'guard_name'   => 'web',
                'group_name'   => 'shifts',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'shift_create',
                'display_name' => 'Create Shift',
                'guard_name'   => 'web',
                'group_name'   => 'shifts',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'shift_edit',
                'display_name' => 'Edit Shift',
                'guard_name'   => 'web',
                'group_name'   => 'shifts',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'shift_delete',
                'display_name' => 'Delete Shift',
                'guard_name'   => 'web',
                'group_name'   => 'shifts',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'shift_show',
                'display_name' => 'View Shift',
                'guard_name'   => 'web',
                'group_name'   => 'shifts',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'shift_toggle_status',
                'display_name' => 'Toggle Shift Status',
                'guard_name'   => 'web',
                'group_name'   => 'shifts',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],

            // Tasks
            [
                'name'         => 'task_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'tasks',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'task_list',
                'display_name' => 'List Tasks',
                'guard_name'   => 'web',
                'group_name'   => 'tasks',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'task_create',
                'display_name' => 'Create Task',
                'guard_name'   => 'web',
                'group_name'   => 'tasks',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'task_edit',
                'display_name' => 'Edit Task',
                'guard_name'   => 'web',
                'group_name'   => 'tasks',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'task_delete',
                'display_name' => 'Delete Task',
                'guard_name'   => 'web',
                'group_name'   => 'tasks',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'task_show',
                'display_name' => 'View Task',
                'guard_name'   => 'web',
                'group_name'   => 'tasks',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'task_toggle_status',
                'display_name' => 'Toggle Task Status',
                'guard_name'   => 'web',
                'group_name'   => 'tasks',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            //  Rosters related permissions
            [
                'name'         => 'roster_list',
                'display_name' => 'Roster List',
                'guard_name'   => 'web',
                'group_name'   => 'rosters',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'assign_roster',
                'display_name' => 'Assign Roster',
                'guard_name'   => 'web',
                'group_name'   => 'rosters',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'edit_assigned_roster',
                'display_name' => 'Edit Roster Assignment',
                'guard_name'   => 'web',
                'group_name'   => 'rosters',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            [
                'name'         => 'view_assigned_roster',
                'display_name' => 'View Roster Assignment details',
                'guard_name'   => 'web',
                'group_name'   => 'rosters',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
             [
                'name'         => 'task_progress_update',
                'display_name' => 'Update Task Progress',
                'guard_name'   => 'web',
                'group_name'   => 'rosters',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],            

            // Performance Analytics
            [
                'name'         => 'performance_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'performance',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
             ],
             [
                'name'         => 'performance_view',
                'display_name' => 'View Performance Analytics',
                'guard_name'   => 'web',
                'group_name'   => 'performance',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
             ],
             
            // Attendance
            [
                'name'         => 'attendance_access',
                'display_name' => 'Menu Access',
                'guard_name'   => 'web',
                'group_name'   => 'attendances',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
            // [
            //     'name'         => 'attendance_list',
            //     'display_name' => 'List Attendances',
            //     'guard_name'   => 'web',
            //     'group_name'   => 'attendances',
            //     'created_at'   => $createDate,
            //     'updated_at'   => $timestamp,
            // ],
            // [
            //     'name'         => 'attendance_create',
            //     'display_name' => 'Create Attendance',
            //     'guard_name'   => 'web',
            //     'group_name'   => 'attendances',
            //     'created_at'   => $createDate,
            //     'updated_at'   => $timestamp,
            // ],
            // [
            //     'name'         => 'attendance_edit',
            //     'display_name' => 'Edit Attendance',
            //     'guard_name'   => 'web',
            //     'group_name'   => 'attendances',
            //     'created_at'   => $createDate,
            //     'updated_at'   => $timestamp,
            // ],
            // [
            //     'name'         => 'attendance_delete',
            //     'display_name' => 'Delete Attendance',
            //     'guard_name'   => 'web',
            //     'group_name'   => 'attendances',
            //     'created_at'   => $createDate,
            //     'updated_at'   => $timestamp,
            // ],
            [
                'name'         => 'attendance_show',
                'display_name' => 'View Attendance',
                'guard_name'   => 'web',
                'group_name'   => 'attendances',
                'created_at'   => $createDate,
                'updated_at'   => $timestamp,
            ],
        ];

        Permission::upsert(
            $permissions,
            ['name', 'guard_name'],                      // unique columns
            ['display_name', 'group_name', 'updated_at'] // columns to update
        );
    }
}
