<div class="row g-4 staff-form-grid">
    <div class="mb-4 col-lg-6">
        <label for="first_name" class="form-label">First Name <span class="text-danger">*</span></label>
        <input type="text" name="first_name" placeholder="First Name" class="form-control" id="first_name"
            value="{{ old('first_name', isset($staff) ? $staff->first_name : '') }}">
        @error('first_name') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="last_name" class="form-label">Last Name</label>
        <input type="text" name="last_name" placeholder="Last Name" class="form-control" id="last_name"
            value="{{ old('last_name', isset($staff) ? $staff->last_name : '') }}">
        @error('last_name') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="email" class="form-label">Email <span class="text-danger">*</span></label>
        <input type="email" name="email" placeholder="Email" class="form-control" id="email"
            value="{{ old('email', isset($staff) ? $staff->email : '') }}">
        @error('email') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="phone" class="form-label">Phone <span class="text-danger">*</span></label>
        <input type="text" name="phone" placeholder="Phone" class="form-control" id="phone"
            value="{{ old('phone', isset($staff) ? $staff->phone : '') }}">
        @error('phone') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>

    <div class="mb-4 col-lg-6">
        <label for="designation" class="form-label">Designation <span class="text-danger">*</span></label>
        <input type="text" name="designation" placeholder="Designation" class="form-control" id="designation"
            value="{{ old('designation', isset($staff) ? $staff->designation : '') }}">
        @error('designation') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="joining_date" class="form-label">Joining Date <span class="text-danger">*</span></label>
        <input type="text" placeholder="Select joining date" name="joining_date" class="form-control datepicker"
            id="joining_date" value="{{ old('joining_date', isset($staff) ? $staff->joining_date : '') }}"
            autocomplete="off">
        @error('joining_date') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-12">
        <label class="form-check admin-form-status-toggle mb-0">
            <input class="form-check-input" type="checkbox" name="status" value="1" {{ old('status', isset($staff) ? (int) $staff->status : 1) ? 'checked' : '' }}>
            <span class="form-check-label">Active Status</span>
        </label>
        <p class="text-muted small mt-2">Activate or deactivate this staff account.</p>
    </div>

    @if(!isset($staff))
        <div class="col-12">
            <div class="alert alert-info mt-4">
                <i class="material-icons md-info mr-5"></i>
                An autogenerated password will be sent to the staff member's email address upon creation.
            </div>
        </div>
    @endif

    <div class="col-12 border-top pt-4 mt-4">
        <button type="submit" class="btn btn-primary">
            {{ isset($staff) ? 'Update Staff' : 'Create Staff' }}
        </button>
        <a href="{{ route('admin.staff.index') }}" class="btn btn-light-secondary ms-2">Cancel</a>
    </div>
</div>

@push('scripts')
    <script>
        flatpickr(".datepicker", {
            dateFormat: "Y-m-d",
            maxDate: "today"
        });
    </script>
@endpush