<div class="row g-4 user-form-grid">
    <div class="mb-4 col-lg-6">
        <label for="first_name" class="form-label">First Name <span class="text-danger">*</span></label>
        <input type="text" name="first_name" placeholder="First Name" class="form-control" id="first_name"
            value="{{ old('first_name', isset($user) ? $user->first_name : '') }}">
        @error('first_name') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="last_name" class="form-label">Last Name</label>
        <input type="text" name="last_name" placeholder="Last Name" class="form-control" id="last_name"
            value="{{ old('last_name', isset($user) ? $user->last_name : '') }}">
        @error('last_name') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="email" class="form-label">Email <span class="text-danger">*</span></label>
        <input type="email" name="email" placeholder="Email" class="form-control" id="email"
            value="{{ old('email', isset($user) ? $user->email : '') }}" {{ isset($user->email) ? 'readonly' : '' }}>
        @error('email') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="phone" class="form-label">Phone <span class="text-danger">*</span></label>
        <input type="text" name="phone" placeholder="Phone" class="form-control" id="phone"
            value="{{ old('phone', isset($user) ? $user->phone : '') }}" {{ isset($user->phone) ? 'readonly' : '' }}>
        @error('phone') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>

    <div class="mb-4 col-lg-6">
        <label for="roles" class="form-label">Assign Roles <span class="text-danger">*</span></label>
        <select name="roles[]" id="roles" class="form-select select2" multiple>
            @foreach($roles as $role)
                <option value="{{ $role->name }}" {{ isset($user) && $user->hasRole($role->name) ? 'selected' : '' }}>
                    {{ ucfirst($role->name) }}
                </option>
            @endforeach
        </select>
        @error('roles')
            <span class="text-danger small">{{ $message }}</span>
        @enderror
    </div>

    <div class="mb-4 col-lg-6">
        <label for="designation" class="form-label">Designation <span class="text-danger">*</span></label>
        <input type="text" name="designation" placeholder="Designation" class="form-control" id="designation"
            value="{{ old('designation', isset($user) ? $user->designation : '') }}">
        @error('designation') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-lg-6">
        <label for="joining_date" class="form-label">Joining Date <span class="text-danger">*</span></label>
        <input type="text" placeholder="Select joining date" name="joining_date" class="form-control datepicker"
            id="joining_date" value="{{ old('joining_date', isset($user) ? $user->joining_date : '') }}"
            autocomplete="off">
        @error('joining_date') <span class="text-danger small">{{ $message }}</span> @enderror
    </div>
    <div class="mb-4 col-12">
        <label class="form-check admin-form-status-toggle mb-0">
            <input class="form-check-input" type="checkbox" name="status" value="1" {{ old('status', isset($user) ? (int) $user->status : 1) ? 'checked' : '' }}>
            <span class="form-check-label"> Active Status</span>
        </label>
        <p class="text-muted small mt-2">Activate or deactivate this user account.</p>
    </div>

    @if(!isset($user))
        <div class="col-12">
            <div class="alert alert-info mt-4">
                <i class="material-icons md-info mr-5"></i>
                An autogenerated password will be sent to the user's email address upon creation.
            </div>
        </div>
    @endif

    <div class="col-12 border-top pt-4 mt-4">
        <button type="submit" class="btn btn-primary">
            {{ isset($user) ? 'Update' : 'Save' }}
        </button>
        <a href="{{ route('admin.user.index') }}" class="btn btn-light-secondary ms-2">Cancel</a>
    </div>
</div>

@include('admin.user.partials.script')